# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ls '$(Build.SourcesDirectory)\DevOpsBrosShop'
- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    command: build
    projects: 'DevOpsBrosShop.csproj'
    workingDirectory: '$(Build.SourcesDirectory)\DevOpsBrosShop'
    
- task: DotNetCoreCLI@2
  displayName: Test project
  inputs:
    command: test
    projects: '**\*.Tests.csproj'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TEST-*.xml'
