# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    command: build
    projects: 'DevOpsBrosShop.sln'
    arguments: '--output "$(Build.ArtifactStagingDirectory)"'
    
- task: DotNetCoreCLI@2
  displayName: Test project
  inputs:
    command: test
    projects: '**/*.Tests.csproj'

- task: CopyFiles@2
  displayName: Copy CreateWebApp script
  inputs:
      OverWrite: true
      Contents: 'CreateWebApp.azcli'
      SourceFolder: '$(Build.SourcesDirectory)'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'       

- task: PublishBuildArtifacts@1
  displayName: Drop artifact
  inputs:
    ArtifactName: drop
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
